-- ChamaEntrega - MySQL 8.0.21+ target schema
-- Generated from the live Supabase/PostgreSQL public schema on 2026-09-25.
-- NON-DESTRUCTIVE: production remains on Supabase during migration.
-- UUID values must be generated by the ChamaEntrega API before INSERT.

SET NAMES utf8mb4;
SET time_zone = '+00:00';
SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------------------------------
-- profiles
-- -----------------------------------------------------------------------------
CREATE TABLE `profiles` (
  `id` CHAR(36) NOT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT 'courier',
  CONSTRAINT `chk_profiles_role` CHECK (`role` IN ('courier', 'store_owner', 'admin')),
  `full_name` VARCHAR(255) NULL,
  `phone` VARCHAR(255) NULL,
  `avatar_url` TEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- couriers
-- -----------------------------------------------------------------------------
CREATE TABLE `couriers` (
  `id` CHAR(36) NOT NULL,
  `vehicle_type` VARCHAR(255) NOT NULL DEFAULT 'motorcycle',
  CONSTRAINT `chk_couriers_vehicle_type` CHECK (`vehicle_type` IN ('motorcycle', 'bike', 'car')),
  `is_online` BOOLEAN NOT NULL DEFAULT FALSE,
  `is_available` BOOLEAN NOT NULL DEFAULT TRUE,
  `rating` DECIMAL(3,2) NOT NULL DEFAULT 5.00,
  CONSTRAINT `chk_couriers_rating` CHECK (`rating` >= 0 AND `rating` <= 5),
  `total_deliveries` INT NOT NULL DEFAULT 0,
  CONSTRAINT `chk_couriers_total_deliveries` CHECK (`total_deliveries` >= 0),
  `current_latitude` DOUBLE NULL,
  `current_longitude` DOUBLE NULL,
  `last_location_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `moderation_status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  CONSTRAINT `chk_couriers_moderation_status` CHECK (`moderation_status` IN ('pending', 'active', 'suspended', 'banned', 'rejected')),
  `moderation_reason` TEXT NULL,
  `moderated_at` DATETIME(6) NULL,
  `moderated_by` CHAR(36) NULL,
  `approved_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- stores
-- -----------------------------------------------------------------------------
CREATE TABLE `stores` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `logo_url` TEXT NULL,
  `address` TEXT NOT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `zip_code` VARCHAR(255) NULL,
  `street` VARCHAR(255) NULL,
  `street_number` VARCHAR(255) NULL,
  `complement` VARCHAR(255) NULL,
  `neighborhood` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(255) NULL,
  `organization_id` CHAR(36) NULL,
  `moderation_status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  CONSTRAINT `chk_stores_moderation_status` CHECK (`moderation_status` IN ('pending', 'active', 'suspended', 'banned', 'rejected')),
  `moderation_reason` TEXT NULL,
  `moderated_at` DATETIME(6) NULL,
  `moderated_by` CHAR(36) NULL,
  `approved_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- deliveries
-- -----------------------------------------------------------------------------
CREATE TABLE `deliveries` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `assigned_courier_id` CHAR(36) NULL,
  `external_order_id` VARCHAR(255) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'draft',
  CONSTRAINT `chk_deliveries_status` CHECK (`status` IN ('draft', 'available', 'negotiating', 'accepted', 'heading_to_pickup', 'at_pickup', 'heading_to_dropoff', 'at_dropoff', 'completed', 'cancelled', 'expired')),
  `pickup_address` TEXT NOT NULL,
  `pickup_latitude` DOUBLE NULL,
  `pickup_longitude` DOUBLE NULL,
  `delivery_address` TEXT NOT NULL,
  `delivery_latitude` DOUBLE NULL,
  `delivery_longitude` DOUBLE NULL,
  `delivery_fee` DECIMAL(10,2) NOT NULL,
  CONSTRAINT `chk_deliveries_delivery_fee` CHECK (`delivery_fee` >= 0),
  `pickup_distance_km` DECIMAL(8,2) NULL,
  CONSTRAINT `chk_deliveries_pickup_distance_km` CHECK (`pickup_distance_km` IS NULL OR `pickup_distance_km` >= 0),
  `delivery_distance_km` DECIMAL(8,2) NULL,
  CONSTRAINT `chk_deliveries_delivery_distance_km` CHECK (`delivery_distance_km` IS NULL OR `delivery_distance_km` >= 0),
  `estimated_minutes` INT NULL,
  CONSTRAINT `chk_deliveries_estimated_minutes` CHECK (`estimated_minutes` IS NULL OR `estimated_minutes` >= 0),
  `payment_method` VARCHAR(255) NOT NULL DEFAULT 'already_paid',
  CONSTRAINT `chk_deliveries_payment_method` CHECK (`payment_method` IN ('already_paid', 'cash', 'pix', 'card_on_delivery')),
  `order_total` DECIMAL(10,2) NULL,
  CONSTRAINT `chk_deliveries_order_total` CHECK (`order_total` IS NULL OR `order_total` >= 0),
  `customer_name` VARCHAR(255) NULL,
  `customer_phone` VARCHAR(255) NULL,
  `customer_note` TEXT NULL,
  `item_count` INT NOT NULL DEFAULT 1,
  CONSTRAINT `chk_deliveries_item_count` CHECK (`item_count` >= 1),
  `package_weight_kg` DECIMAL(8,2) NULL,
  CONSTRAINT `chk_deliveries_package_weight_kg` CHECK (`package_weight_kg` IS NULL OR `package_weight_kg` >= 0),
  `seconds_to_accept` INT NOT NULL DEFAULT 30,
  CONSTRAINT `chk_deliveries_seconds_to_accept` CHECK (`seconds_to_accept` >= 10),
  `published_at` DATETIME(6) NULL,
  `expires_at` DATETIME(6) NULL,
  `accepted_at` DATETIME(6) NULL,
  `completed_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `courier_batch_id` CHAR(36) NULL,
  `ready_at` DATETIME(6) NULL,
  `target_courier_id` CHAR(36) NULL,
  `dispatch_route_group_id` CHAR(36) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- delivery_offer_responses
-- -----------------------------------------------------------------------------
CREATE TABLE `delivery_offer_responses` (
  `id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `response` TEXT NOT NULL,
  CONSTRAINT `chk_delivery_offer_responses_response` CHECK (`response` IN ('accepted', 'rejected', 'countered', 'expired')),
  `reason` TEXT NULL,
  `counter_amount` DECIMAL(10,2) NULL,
  CONSTRAINT `chk_delivery_offer_responses_counter_amount` CHECK (`counter_amount` IS NULL OR `counter_amount` > 0),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- delivery_status_history
-- -----------------------------------------------------------------------------
CREATE TABLE `delivery_status_history` (
  `id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `changed_by` CHAR(36) NULL,
  `note` TEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- courier_delivery_batches
-- -----------------------------------------------------------------------------
CREATE TABLE `courier_delivery_batches` (
  `id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'open',
  CONSTRAINT `chk_courier_delivery_batches_status` CHECK (`status` IN ('open', 'locked', 'completed')),
  `max_deliveries` SMALLINT NOT NULL DEFAULT 3,
  CONSTRAINT `chk_courier_delivery_batches_max_deliveries` CHECK (`max_deliveries` >= 1 AND `max_deliveries` <= 3),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `completed_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- courier_push_tokens
-- -----------------------------------------------------------------------------
CREATE TABLE `courier_push_tokens` (
  `token` VARCHAR(512) NOT NULL,
  CONSTRAINT `chk_courier_push_tokens_token` CHECK (char_length(`token`) >= 20),
  `courier_id` CHAR(36) NOT NULL,
  `platform` VARCHAR(255) NOT NULL DEFAULT 'android',
  CONSTRAINT `chk_courier_push_tokens_platform` CHECK (`platform` IN ('android', 'ios', 'web')),
  `app_package` VARCHAR(255) NOT NULL DEFAULT 'com.marciodiaz.logistica.entregador',
  `device_name` VARCHAR(255) NULL,
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `last_seen_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `id` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- delivery_location_confirmations
-- -----------------------------------------------------------------------------
CREATE TABLE `delivery_location_confirmations` (
  `id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `confirmation_type` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_delivery_location_confirmations_confirmation_type` CHECK (`confirmation_type` IN ('pickup_arrival', 'dropoff_arrival')),
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `accuracy_meters` DOUBLE NOT NULL,
  `target_latitude` DOUBLE NOT NULL,
  `target_longitude` DOUBLE NOT NULL,
  `distance_meters` DOUBLE NOT NULL,
  `allowed_radius_meters` DOUBLE NOT NULL DEFAULT 120,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- courier_store_networks
-- -----------------------------------------------------------------------------
CREATE TABLE `courier_store_networks` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  CONSTRAINT `chk_courier_store_networks_status` CHECK (`status` IN ('pending', 'connected', 'rejected')),
  `requested_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `reviewed_at` DATETIME(6) NULL,
  `reviewed_by` CHAR(36) NULL,
  `review_note` TEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- delivery_payments
-- -----------------------------------------------------------------------------
CREATE TABLE `delivery_payments` (
  `id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  CONSTRAINT `chk_delivery_payments_amount` CHECK (`amount` >= 0),
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  CONSTRAINT `chk_delivery_payments_status` CHECK (`status` IN ('pending', 'sent', 'received', 'disputed')),
  `payment_method` VARCHAR(255) NOT NULL DEFAULT 'pix',
  CONSTRAINT `chk_delivery_payments_payment_method` CHECK (`payment_method` IN ('pix', 'cash', 'other')),
  `delivery_completed_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `store_marked_sent_at` DATETIME(6) NULL,
  `courier_confirmed_at` DATETIME(6) NULL,
  `proof_url` TEXT NULL,
  `note` TEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- delivery_chat_messages
-- -----------------------------------------------------------------------------
CREATE TABLE `delivery_chat_messages` (
  `id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `sender_id` CHAR(36) NOT NULL,
  `sender_role` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_delivery_chat_messages_sender_role` CHECK (`sender_role` IN ('courier', 'store', 'admin')),
  `body` TEXT NOT NULL,
  CONSTRAINT `chk_delivery_chat_messages_body` CHECK (char_length(TRIM(`body`)) >= 1 AND char_length(TRIM(`body`)) <= 1000),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `read_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- courier_ratings
-- -----------------------------------------------------------------------------
CREATE TABLE `courier_ratings` (
  `id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `score` SMALLINT NOT NULL,
  CONSTRAINT `chk_courier_ratings_score` CHECK (`score` >= 1 AND `score` <= 5),
  `comment` TEXT NULL,
  CONSTRAINT `chk_courier_ratings_comment` CHECK (`comment` IS NULL OR char_length(`comment`) <= 1000),
  `tags` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  CONSTRAINT `chk_courier_ratings_tags` CHECK (JSON_LENGTH(`tags`) <= 8),
  `created_by` CHAR(36) NULL,
  `is_test` BOOLEAN NOT NULL DEFAULT FALSE,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- delivery_incidents
-- -----------------------------------------------------------------------------
CREATE TABLE `delivery_incidents` (
  `id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_delivery_incidents_category` CHECK (`category` IN ('order_not_ready', 'store_closed', 'wrong_address', 'customer_absent', 'damaged_order', 'accident', 'other')),
  `description` TEXT NOT NULL,
  CONSTRAINT `chk_delivery_incidents_description` CHECK (char_length(TRIM(`description`)) >= 10 AND char_length(TRIM(`description`)) <= 1500),
  `priority` VARCHAR(255) NOT NULL DEFAULT 'normal',
  CONSTRAINT `chk_delivery_incidents_priority` CHECK (`priority` IN ('normal', 'urgent')),
  `status` VARCHAR(255) NOT NULL DEFAULT 'open',
  CONSTRAINT `chk_delivery_incidents_status` CHECK (`status` IN ('open', 'in_review', 'resolved')),
  `reviewed_by` CHAR(36) NULL,
  `reviewed_at` DATETIME(6) NULL,
  `resolved_at` DATETIME(6) NULL,
  `resolution_note` TEXT NULL,
  CONSTRAINT `chk_delivery_incidents_resolution_note` CHECK (`resolution_note` IS NULL OR char_length(TRIM(`resolution_note`)) <= 1500),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- courier_verifications
-- -----------------------------------------------------------------------------
CREATE TABLE `courier_verifications` (
  `courier_id` CHAR(36) NOT NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'not_started',
  CONSTRAINT `chk_courier_verifications_status` CHECK (`status` IN ('not_started', 'draft', 'under_review', 'approved', 'correction_required')),
  `cnh_front_path` VARCHAR(500) NULL,
  CONSTRAINT `chk_courier_verifications_cnh_front_path` CHECK (`cnh_front_path` IS NULL OR char_length(TRIM(`cnh_front_path`)) >= 5 AND char_length(TRIM(`cnh_front_path`)) <= 500),
  `cnh_back_path` VARCHAR(500) NULL,
  CONSTRAINT `chk_courier_verifications_cnh_back_path` CHECK (`cnh_back_path` IS NULL OR char_length(TRIM(`cnh_back_path`)) >= 5 AND char_length(TRIM(`cnh_back_path`)) <= 500),
  `selfie_path` VARCHAR(500) NULL,
  CONSTRAINT `chk_courier_verifications_selfie_path` CHECK (`selfie_path` IS NULL OR char_length(TRIM(`selfie_path`)) >= 5 AND char_length(TRIM(`selfie_path`)) <= 500),
  `vehicle_document_path` VARCHAR(500) NULL,
  CONSTRAINT `chk_courier_verifications_vehicle_document_path` CHECK (`vehicle_document_path` IS NULL OR char_length(TRIM(`vehicle_document_path`)) >= 5 AND char_length(TRIM(`vehicle_document_path`)) <= 500),
  `cnh_expiry_date` DATE NULL,
  `submitted_at` DATETIME(6) NULL,
  `reviewed_by` CHAR(36) NULL,
  `reviewed_at` DATETIME(6) NULL,
  `review_note` TEXT NULL,
  CONSTRAINT `chk_courier_verifications_review_note` CHECK (`review_note` IS NULL OR char_length(TRIM(`review_note`)) >= 1 AND char_length(TRIM(`review_note`)) <= 1500),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`courier_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- courier_support_tickets
-- -----------------------------------------------------------------------------
CREATE TABLE `courier_support_tickets` (
  `id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NULL,
  `delivery_reference` VARCHAR(255) NULL,
  CONSTRAINT `chk_courier_support_tickets_delivery_reference` CHECK (`delivery_reference` IS NULL OR char_length(TRIM(`delivery_reference`)) >= 1 AND char_length(TRIM(`delivery_reference`)) <= 100),
  `category` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_courier_support_tickets_category` CHECK (`category` IN ('delivery', 'payment', 'account', 'documents', 'safety', 'app', 'other')),
  `priority` VARCHAR(255) NOT NULL DEFAULT 'normal',
  CONSTRAINT `chk_courier_support_tickets_priority` CHECK (`priority` IN ('normal', 'high', 'urgent')),
  `status` VARCHAR(255) NOT NULL DEFAULT 'open',
  CONSTRAINT `chk_courier_support_tickets_status` CHECK (`status` IN ('open', 'in_progress', 'waiting_courier', 'resolved')),
  `subject` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_courier_support_tickets_subject` CHECK (char_length(TRIM(`subject`)) >= 5 AND char_length(TRIM(`subject`)) <= 100),
  `description` TEXT NOT NULL,
  CONSTRAINT `chk_courier_support_tickets_description` CHECK (char_length(TRIM(`description`)) >= 10 AND char_length(TRIM(`description`)) <= 2000),
  `support_response` TEXT NULL,
  CONSTRAINT `chk_courier_support_tickets_support_response` CHECK (`support_response` IS NULL OR char_length(TRIM(`support_response`)) >= 1 AND char_length(TRIM(`support_response`)) <= 4000),
  `support_responded_at` DATETIME(6) NULL,
  `resolved_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- courier_push_dispatches
-- -----------------------------------------------------------------------------
CREATE TABLE `courier_push_dispatches` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_key` VARCHAR(255) NOT NULL,
  `token_id` VARCHAR(255) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `notification_type` VARCHAR(255) NOT NULL,
  `fcm_message_name` TEXT NULL,
  `sent_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- store_wallets
-- -----------------------------------------------------------------------------
CREATE TABLE `store_wallets` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `balance` DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT `chk_store_wallets_balance` CHECK (`balance` >= 0),
  `reserved_balance` DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT `chk_store_wallets_reserved_balance` CHECK (`reserved_balance` >= 0),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- store_wallet_transactions
-- -----------------------------------------------------------------------------
CREATE TABLE `store_wallet_transactions` (
  `id` CHAR(36) NOT NULL,
  `wallet_id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `transaction_type` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_store_wallet_transactions_transaction_type` CHECK (`transaction_type` IN ('deposit', 'delivery_payment', 'refund', 'withdrawal', 'adjustment', 'bonus')),
  `direction` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_store_wallet_transactions_direction` CHECK (`direction` IN ('credit', 'debit')),
  `amount` DECIMAL(12,2) NOT NULL,
  CONSTRAINT `chk_store_wallet_transactions_amount` CHECK (`amount` > 0),
  `status` VARCHAR(255) NOT NULL DEFAULT 'completed',
  CONSTRAINT `chk_store_wallet_transactions_status` CHECK (`status` IN ('pending', 'completed', 'failed', 'cancelled')),
  `description` TEXT NULL,
  `reference_type` VARCHAR(255) NULL,
  `reference_id` VARCHAR(255) NULL,
  `balance_before` DECIMAL(12,2) NULL,
  `balance_after` DECIMAL(12,2) NULL,
  `metadata` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `completed_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- courier_store_messages
-- -----------------------------------------------------------------------------
CREATE TABLE `courier_store_messages` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `sender_id` CHAR(36) NOT NULL,
  `sender_type` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_courier_store_messages_sender_type` CHECK (`sender_type` IN ('store', 'courier')),
  `message` TEXT NOT NULL,
  CONSTRAINT `chk_courier_store_messages_message` CHECK (char_length(TRIM(`message`)) > 0),
  `is_read` BOOLEAN NOT NULL DEFAULT FALSE,
  `read_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- store_wallet_reservations
-- -----------------------------------------------------------------------------
CREATE TABLE `store_wallet_reservations` (
  `id` CHAR(36) NOT NULL,
  `wallet_id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  CONSTRAINT `chk_store_wallet_reservations_amount` CHECK (`amount` > 0),
  `status` VARCHAR(255) NOT NULL DEFAULT 'reserved',
  CONSTRAINT `chk_store_wallet_reservations_status` CHECK (`status` IN ('reserved', 'captured', 'released')),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `captured_at` DATETIME(6) NULL,
  `released_at` DATETIME(6) NULL,
  `metadata` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- store_wallet_topups
-- -----------------------------------------------------------------------------
CREATE TABLE `store_wallet_topups` (
  `id` CHAR(36) NOT NULL,
  `wallet_id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `provider` VARCHAR(255) NOT NULL DEFAULT 'woovi',
  `correlation_id` VARCHAR(255) NOT NULL,
  `provider_charge_id` VARCHAR(255) NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  CONSTRAINT `chk_store_wallet_topups_amount` CHECK (`amount` > 0),
  `status` VARCHAR(255) NOT NULL DEFAULT 'pending',
  CONSTRAINT `chk_store_wallet_topups_status` CHECK (`status` IN ('pending', 'paid', 'expired', 'cancelled', 'failed')),
  `br_code` VARCHAR(255) NULL,
  `qr_code_image_url` TEXT NULL,
  `payment_link_url` TEXT NULL,
  `provider_payload` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `paid_at` DATETIME(6) NULL,
  `expires_at` DATETIME(6) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- store_integrations
-- -----------------------------------------------------------------------------
CREATE TABLE `store_integrations` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `provider` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_store_integrations_provider` CHECK (`provider` IN ('whatsapp', 'ifood', '99food', 'goomer', 'own_menu')),
  `status` VARCHAR(255) NOT NULL DEFAULT 'not_configured',
  CONSTRAINT `chk_store_integrations_status` CHECK (`status` IN ('not_configured', 'configured', 'pending', 'connected', 'error')),
  `is_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
  `public_config` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  CONSTRAINT `chk_store_integrations_public_config` CHECK (JSON_TYPE(`public_config`) = 'OBJECT'),
  `last_synced_at` DATETIME(6) NULL,
  `last_error` TEXT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- store_orders
-- -----------------------------------------------------------------------------
CREATE TABLE `store_orders` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `source` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_store_orders_source` CHECK (`source` IN ('whatsapp', 'ifood', '99food', 'goomer', 'own_menu', 'manual')),
  `external_order_id` VARCHAR(255) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'new',
  CONSTRAINT `chk_store_orders_status` CHECK (`status` IN ('new', 'preparing', 'ready', 'seeking_courier', 'in_route', 'completed', 'cancelled')),
  `fulfillment_type` VARCHAR(255) NOT NULL DEFAULT 'delivery',
  CONSTRAINT `chk_store_orders_fulfillment_type` CHECK (`fulfillment_type` IN ('delivery', 'pickup')),
  `customer_name` VARCHAR(255) NULL,
  `customer_phone` VARCHAR(255) NULL,
  `delivery_address` TEXT NULL,
  `delivery_latitude` DOUBLE NULL,
  `delivery_longitude` DOUBLE NULL,
  `items` JSON NOT NULL DEFAULT (JSON_ARRAY()),
  CONSTRAINT `chk_store_orders_items` CHECK (JSON_TYPE(`items`) = 'ARRAY'),
  `order_total` DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT `chk_store_orders_order_total` CHECK (`order_total` >= 0),
  `payment_method` VARCHAR(255) NOT NULL DEFAULT 'unknown',
  `payment_status` VARCHAR(255) NOT NULL DEFAULT 'unknown',
  CONSTRAINT `chk_store_orders_payment_status` CHECK (`payment_status` IN ('unknown', 'pending', 'paid', 'failed', 'refunded')),
  `customer_note` TEXT NULL,
  `delivery_id` CHAR(36) NULL,
  `source_metadata` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  CONSTRAINT `chk_store_orders_source_metadata` CHECK (JSON_TYPE(`source_metadata`) = 'OBJECT'),
  `received_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- whatsapp_conversations
-- -----------------------------------------------------------------------------
CREATE TABLE `whatsapp_conversations` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `wa_id` VARCHAR(255) NOT NULL,
  `customer_name` VARCHAR(255) NULL,
  `customer_phone` VARCHAR(255) NULL,
  `active_order_id` CHAR(36) NULL,
  `status` VARCHAR(255) NOT NULL DEFAULT 'open',
  CONSTRAINT `chk_whatsapp_conversations_status` CHECK (`status` IN ('open', 'archived')),
  `last_message_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- whatsapp_messages
-- -----------------------------------------------------------------------------
CREATE TABLE `whatsapp_messages` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `conversation_id` CHAR(36) NOT NULL,
  `provider_message_id` VARCHAR(255) NOT NULL,
  `wa_id` VARCHAR(255) NOT NULL,
  `message_type` TEXT NOT NULL,
  `body` TEXT NULL,
  `provider_payload` JSON NOT NULL DEFAULT (JSON_OBJECT()),
  CONSTRAINT `chk_whatsapp_messages_provider_payload` CHECK (JSON_TYPE(`provider_payload`) = 'OBJECT'),
  `received_at` DATETIME(6) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- whatsapp_connection_credentials
-- -----------------------------------------------------------------------------
CREATE TABLE `whatsapp_connection_credentials` (
  `store_id` CHAR(36) NOT NULL,
  `waba_id` VARCHAR(255) NOT NULL,
  `phone_number_id` VARCHAR(255) NOT NULL,
  `display_phone_number` VARCHAR(255) NULL,
  `verified_name` VARCHAR(255) NULL,
  `token_type` VARCHAR(255) NULL,
  `token_expires_at` DATETIME(6) NULL,
  `connected_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `access_token_secret_id` CHAR(36) NOT NULL,
  PRIMARY KEY (`store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- delivery_location_points
-- -----------------------------------------------------------------------------
CREATE TABLE `delivery_location_points` (
  `id` CHAR(36) NOT NULL,
  `delivery_id` CHAR(36) NOT NULL,
  `courier_id` CHAR(36) NOT NULL,
  `latitude` DOUBLE NOT NULL,
  CONSTRAINT `chk_delivery_location_points_latitude` CHECK (`latitude` >= '-90' AND `latitude` <= 90),
  `longitude` DOUBLE NOT NULL,
  CONSTRAINT `chk_delivery_location_points_longitude` CHECK (`longitude` >= '-180' AND `longitude` <= 180),
  `accuracy_meters` DOUBLE NULL,
  CONSTRAINT `chk_delivery_location_points_accuracy_meters` CHECK (`accuracy_meters` IS NULL OR `accuracy_meters` >= 0),
  `recorded_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- delivery_pricing_settings
-- -----------------------------------------------------------------------------
CREATE TABLE `delivery_pricing_settings` (
  `store_id` CHAR(36) NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT TRUE,
  `minimum_fee` DECIMAL(10,2) NOT NULL DEFAULT 7.50,
  CONSTRAINT `chk_delivery_pricing_settings_minimum_fee` CHECK (`minimum_fee` >= 0),
  `included_km` DECIMAL(8,2) NOT NULL DEFAULT 2.00,
  CONSTRAINT `chk_delivery_pricing_settings_included_km` CHECK (`included_km` >= 0),
  `per_extra_km` DECIMAL(10,2) NOT NULL DEFAULT 1.50,
  CONSTRAINT `chk_delivery_pricing_settings_per_extra_km` CHECK (`per_extra_km` >= 0),
  `road_factor` DECIMAL(6,3) NOT NULL DEFAULT 1.250,
  CONSTRAINT `chk_delivery_pricing_settings_road_factor` CHECK (`road_factor` >= 1),
  `round_step` DECIMAL(10,2) NOT NULL DEFAULT 0.50,
  CONSTRAINT `chk_delivery_pricing_settings_round_step` CHECK (`round_step` > 0),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`store_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- organizations
-- -----------------------------------------------------------------------------
CREATE TABLE `organizations` (
  `id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `legal_name` VARCHAR(255) NULL,
  `tax_id` VARCHAR(255) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- organization_members
-- -----------------------------------------------------------------------------
CREATE TABLE `organization_members` (
  `organization_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT 'member',
  CONSTRAINT `chk_organization_members_role` CHECK (`role` IN ('owner', 'admin', 'manager', 'finance', 'operator')),
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  CONSTRAINT `chk_organization_members_status` CHECK (`status` IN ('active', 'invited', 'disabled')),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`organization_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- store_members
-- -----------------------------------------------------------------------------
CREATE TABLE `store_members` (
  `store_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `role` VARCHAR(255) NOT NULL DEFAULT 'operator',
  CONSTRAINT `chk_store_members_role` CHECK (`role` IN ('owner', 'admin', 'manager', 'finance', 'operator')),
  `status` VARCHAR(255) NOT NULL DEFAULT 'active',
  CONSTRAINT `chk_store_members_status` CHECK (`status` IN ('active', 'invited', 'disabled')),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`store_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- platform_billing_settings
-- -----------------------------------------------------------------------------
CREATE TABLE `platform_billing_settings` (
  `id` SMALLINT NOT NULL DEFAULT 1,
  CONSTRAINT `chk_platform_billing_settings_id` CHECK (`id` = 1),
  `commission_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
  `delivery_commission_percent` DECIMAL(5,2) NOT NULL DEFAULT 0,
  CONSTRAINT `chk_platform_billing_settings_delivery_commission_percent` CHECK (`delivery_commission_percent` >= 0 AND `delivery_commission_percent` <= 100),
  `subscriptions_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
  `default_subscription_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT `chk_platform_billing_settings_default_subscription_amount` CHECK (`default_subscription_amount` >= 0),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_by` CHAR(36) NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- store_subscriptions
-- -----------------------------------------------------------------------------
CREATE TABLE `store_subscriptions` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NOT NULL,
  `plan_name` VARCHAR(255) NOT NULL DEFAULT 'Plano ChamaEntrega',
  `monthly_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT `chk_store_subscriptions_monthly_amount` CHECK (`monthly_amount` >= 0),
  `status` VARCHAR(255) NOT NULL DEFAULT 'inactive',
  CONSTRAINT `chk_store_subscriptions_status` CHECK (`status` IN ('inactive', 'trialing', 'active', 'paused', 'cancelled')),
  `started_at` DATETIME(6) NULL,
  `next_billing_at` DATETIME(6) NULL,
  `last_billed_at` DATETIME(6) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- platform_revenue_events
-- -----------------------------------------------------------------------------
CREATE TABLE `platform_revenue_events` (
  `id` CHAR(36) NOT NULL,
  `store_id` CHAR(36) NULL,
  `delivery_id` CHAR(36) NULL,
  `subscription_id` CHAR(36) NULL,
  `revenue_type` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_platform_revenue_events_revenue_type` CHECK (`revenue_type` IN ('delivery_commission', 'subscription', 'adjustment')),
  `gross_reference_amount` DECIMAL(12,2) NOT NULL DEFAULT 0,
  `rate_percent` DECIMAL(5,2) NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  CONSTRAINT `chk_platform_revenue_events_amount` CHECK (`amount` >= 0),
  `status` VARCHAR(255) NOT NULL DEFAULT 'accrued',
  CONSTRAINT `chk_platform_revenue_events_status` CHECK (`status` IN ('accrued', 'paid', 'void')),
  `description` TEXT NULL,
  `occurred_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- admin_moderation_events
-- -----------------------------------------------------------------------------
CREATE TABLE `admin_moderation_events` (
  `id` CHAR(36) NOT NULL,
  `subject_type` VARCHAR(255) NOT NULL,
  CONSTRAINT `chk_admin_moderation_events_subject_type` CHECK (`subject_type` IN ('store', 'courier')),
  `subject_id` CHAR(36) NOT NULL,
  `previous_status` VARCHAR(255) NULL,
  `new_status` VARCHAR(255) NOT NULL,
  `reason` TEXT NULL,
  `admin_id` CHAR(36) NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- -----------------------------------------------------------------------------
-- Foreign keys
-- -----------------------------------------------------------------------------
ALTER TABLE `admin_moderation_events` ADD CONSTRAINT `admin_moderation_events_admin_id_fkey` FOREIGN KEY (`admin_id`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
-- SKIPPED courier_push_dispatches_courier_id_fkey: courier_push_dispatches -> auth.users; handled by the future auth service.
ALTER TABLE `courier_push_tokens` ADD CONSTRAINT `courier_push_tokens_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `courier_ratings` ADD CONSTRAINT `courier_ratings_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `courier_ratings` ADD CONSTRAINT `courier_ratings_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `courier_ratings` ADD CONSTRAINT `courier_ratings_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `courier_ratings` ADD CONSTRAINT `courier_ratings_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `courier_store_messages` ADD CONSTRAINT `courier_store_messages_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
-- SKIPPED courier_store_messages_sender_id_fkey: courier_store_messages -> auth.users; handled by the future auth service.
ALTER TABLE `courier_store_messages` ADD CONSTRAINT `courier_store_messages_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `courier_store_networks` ADD CONSTRAINT `courier_store_networks_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `courier_store_networks` ADD CONSTRAINT `courier_store_networks_reviewed_by_fkey` FOREIGN KEY (`reviewed_by`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `courier_store_networks` ADD CONSTRAINT `courier_store_networks_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
-- SKIPPED courier_support_tickets_courier_id_fkey: courier_support_tickets -> auth.users; handled by the future auth service.
ALTER TABLE `courier_support_tickets` ADD CONSTRAINT `courier_support_tickets_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `courier_verifications` ADD CONSTRAINT `courier_verifications_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `courier_verifications` ADD CONSTRAINT `courier_verifications_reviewed_by_fkey` FOREIGN KEY (`reviewed_by`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `couriers` ADD CONSTRAINT `couriers_id_fkey` FOREIGN KEY (`id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `couriers` ADD CONSTRAINT `couriers_moderated_by_fkey` FOREIGN KEY (`moderated_by`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `deliveries` ADD CONSTRAINT `deliveries_assigned_courier_id_fkey` FOREIGN KEY (`assigned_courier_id`) REFERENCES `couriers` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `deliveries` ADD CONSTRAINT `deliveries_courier_batch_id_fkey` FOREIGN KEY (`courier_batch_id`) REFERENCES `courier_delivery_batches` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `deliveries` ADD CONSTRAINT `deliveries_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `deliveries` ADD CONSTRAINT `deliveries_target_courier_id_fkey` FOREIGN KEY (`target_courier_id`) REFERENCES `couriers` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `delivery_chat_messages` ADD CONSTRAINT `delivery_chat_messages_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_chat_messages` ADD CONSTRAINT `delivery_chat_messages_sender_id_fkey` FOREIGN KEY (`sender_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_incidents` ADD CONSTRAINT `delivery_incidents_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_incidents` ADD CONSTRAINT `delivery_incidents_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_incidents` ADD CONSTRAINT `delivery_incidents_reviewed_by_fkey` FOREIGN KEY (`reviewed_by`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `delivery_incidents` ADD CONSTRAINT `delivery_incidents_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_location_confirmations` ADD CONSTRAINT `delivery_location_confirmations_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_location_confirmations` ADD CONSTRAINT `delivery_location_confirmations_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_location_points` ADD CONSTRAINT `delivery_location_points_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_location_points` ADD CONSTRAINT `delivery_location_points_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_offer_responses` ADD CONSTRAINT `delivery_offer_responses_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_offer_responses` ADD CONSTRAINT `delivery_offer_responses_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_payments` ADD CONSTRAINT `delivery_payments_courier_id_fkey` FOREIGN KEY (`courier_id`) REFERENCES `couriers` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_payments` ADD CONSTRAINT `delivery_payments_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_payments` ADD CONSTRAINT `delivery_payments_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_pricing_settings` ADD CONSTRAINT `delivery_pricing_settings_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `delivery_status_history` ADD CONSTRAINT `delivery_status_history_changed_by_fkey` FOREIGN KEY (`changed_by`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `delivery_status_history` ADD CONSTRAINT `delivery_status_history_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `organization_members` ADD CONSTRAINT `organization_members_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `organization_members` ADD CONSTRAINT `organization_members_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `organizations` ADD CONSTRAINT `organizations_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `profiles` (`id`) ON DELETE RESTRICT ON UPDATE NO ACTION;
ALTER TABLE `platform_billing_settings` ADD CONSTRAINT `platform_billing_settings_updated_by_fkey` FOREIGN KEY (`updated_by`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `platform_revenue_events` ADD CONSTRAINT `platform_revenue_events_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `platform_revenue_events` ADD CONSTRAINT `platform_revenue_events_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `platform_revenue_events` ADD CONSTRAINT `platform_revenue_events_subscription_id_fkey` FOREIGN KEY (`subscription_id`) REFERENCES `store_subscriptions` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
-- SKIPPED profiles_id_fkey: profiles -> auth.users; handled by the future auth service.
ALTER TABLE `store_integrations` ADD CONSTRAINT `store_integrations_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_members` ADD CONSTRAINT `store_members_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_members` ADD CONSTRAINT `store_members_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_orders` ADD CONSTRAINT `store_orders_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `store_orders` ADD CONSTRAINT `store_orders_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_subscriptions` ADD CONSTRAINT `store_subscriptions_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_wallet_reservations` ADD CONSTRAINT `store_wallet_reservations_delivery_id_fkey` FOREIGN KEY (`delivery_id`) REFERENCES `deliveries` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_wallet_reservations` ADD CONSTRAINT `store_wallet_reservations_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_wallet_reservations` ADD CONSTRAINT `store_wallet_reservations_wallet_id_fkey` FOREIGN KEY (`wallet_id`) REFERENCES `store_wallets` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_wallet_topups` ADD CONSTRAINT `store_wallet_topups_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_wallet_topups` ADD CONSTRAINT `store_wallet_topups_wallet_id_fkey` FOREIGN KEY (`wallet_id`) REFERENCES `store_wallets` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_wallet_transactions` ADD CONSTRAINT `store_wallet_transactions_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_wallet_transactions` ADD CONSTRAINT `store_wallet_transactions_wallet_id_fkey` FOREIGN KEY (`wallet_id`) REFERENCES `store_wallets` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `store_wallets` ADD CONSTRAINT `store_wallets_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `stores` ADD CONSTRAINT `stores_moderated_by_fkey` FOREIGN KEY (`moderated_by`) REFERENCES `profiles` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `stores` ADD CONSTRAINT `stores_organization_id_fkey` FOREIGN KEY (`organization_id`) REFERENCES `organizations` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `stores` ADD CONSTRAINT `stores_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `profiles` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `whatsapp_connection_credentials` ADD CONSTRAINT `whatsapp_connection_credentials_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `whatsapp_conversations` ADD CONSTRAINT `whatsapp_conversations_active_order_id_fkey` FOREIGN KEY (`active_order_id`) REFERENCES `store_orders` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION;
ALTER TABLE `whatsapp_conversations` ADD CONSTRAINT `whatsapp_conversations_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `whatsapp_messages` ADD CONSTRAINT `whatsapp_messages_conversation_id_fkey` FOREIGN KEY (`conversation_id`) REFERENCES `whatsapp_conversations` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `whatsapp_messages` ADD CONSTRAINT `whatsapp_messages_store_id_fkey` FOREIGN KEY (`store_id`) REFERENCES `stores` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION;

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------
CREATE INDEX `admin_moderation_events_admin_id_idx` ON `admin_moderation_events` (admin_id);
CREATE INDEX `idx_admin_moderation_events_subject` ON `admin_moderation_events` (subject_type, subject_id, created_at DESC);
CREATE INDEX `courier_push_dispatches_courier_idx` ON `courier_push_dispatches` (courier_id, sent_at DESC);
CREATE UNIQUE INDEX `courier_push_dispatches_event_key_token_id_key` ON `courier_push_dispatches` (event_key, token_id);
CREATE INDEX `courier_push_dispatches_sent_at_idx` ON `courier_push_dispatches` (sent_at DESC);
CREATE INDEX `courier_push_tokens_courier_active_idx` ON `courier_push_tokens` (courier_id, is_active, app_package);
CREATE INDEX `courier_push_tokens_courier_id_idx` ON `courier_push_tokens` (courier_id);
CREATE UNIQUE INDEX `courier_push_tokens_token_uidx` ON `courier_push_tokens` (token);
CREATE INDEX `courier_ratings_courier_created_idx` ON `courier_ratings` (courier_id, created_at DESC);
CREATE INDEX `courier_ratings_created_by_idx` ON `courier_ratings` (created_by);
CREATE UNIQUE INDEX `courier_ratings_delivery_unique` ON `courier_ratings` (delivery_id);
CREATE INDEX `courier_ratings_score_idx` ON `courier_ratings` (score);
CREATE INDEX `courier_ratings_store_created_idx` ON `courier_ratings` (store_id, created_at DESC);
CREATE INDEX `courier_store_messages_courier_id_idx` ON `courier_store_messages` (courier_id);
CREATE INDEX `courier_store_messages_sender_id_idx` ON `courier_store_messages` (sender_id);
CREATE INDEX `courier_store_messages_store_courier_created_idx` ON `courier_store_messages` (store_id, courier_id, created_at);
CREATE INDEX `courier_store_networks_courier_idx` ON `courier_store_networks` (courier_id);
CREATE UNIQUE INDEX `courier_store_networks_courier_store_unique` ON `courier_store_networks` (courier_id, store_id);
CREATE INDEX `courier_store_networks_reviewed_by_idx` ON `courier_store_networks` (reviewed_by);
CREATE INDEX `courier_store_networks_status_idx` ON `courier_store_networks` (status);
CREATE INDEX `courier_store_networks_store_idx` ON `courier_store_networks` (store_id);
CREATE INDEX `courier_support_tickets_courier_updated_idx` ON `courier_support_tickets` (courier_id, updated_at DESC);
CREATE INDEX `courier_support_tickets_status_updated_idx` ON `courier_support_tickets` (status, updated_at DESC);
CREATE INDEX `courier_verifications_reviewed_by_idx` ON `courier_verifications` (reviewed_by);
CREATE INDEX `courier_verifications_status_updated_idx` ON `courier_verifications` (status, updated_at DESC);
CREATE INDEX `couriers_moderated_by_idx` ON `couriers` (moderated_by);
CREATE INDEX `deliveries_assigned_courier_status_idx` ON `deliveries` (assigned_courier_id, status);
CREATE INDEX `deliveries_courier_batch_id_idx` ON `deliveries` (courier_batch_id);
CREATE INDEX `deliveries_courier_index` ON `deliveries` (assigned_courier_id);
CREATE INDEX `deliveries_published_at_index` ON `deliveries` (published_at DESC);
CREATE INDEX `deliveries_status_index` ON `deliveries` (status);
CREATE INDEX `deliveries_store_index` ON `deliveries` (store_id);
CREATE INDEX `deliveries_store_status_created_idx` ON `deliveries` (store_id, status, created_at DESC);
CREATE INDEX `idx_deliveries_dispatch_route_group` ON `deliveries` (dispatch_route_group_id);
CREATE INDEX `idx_deliveries_target_courier_status` ON `deliveries` (target_courier_id, status);
CREATE INDEX `delivery_chat_messages_delivery_created_idx` ON `delivery_chat_messages` (delivery_id, created_at, id);
CREATE INDEX `delivery_chat_messages_sender_id_idx` ON `delivery_chat_messages` (sender_id);
CREATE INDEX `delivery_incidents_courier_created_idx` ON `delivery_incidents` (courier_id, created_at DESC);
CREATE INDEX `delivery_incidents_delivery_idx` ON `delivery_incidents` (delivery_id, created_at DESC);
CREATE INDEX `delivery_incidents_reviewed_by_idx` ON `delivery_incidents` (reviewed_by);
CREATE INDEX `delivery_incidents_status_idx` ON `delivery_incidents` (status, priority, created_at DESC);
CREATE INDEX `delivery_incidents_store_created_idx` ON `delivery_incidents` (store_id, created_at DESC);
CREATE INDEX `delivery_location_confirmations_courier_id_idx` ON `delivery_location_confirmations` (courier_id, created_at DESC);
CREATE INDEX `delivery_location_confirmations_delivery_id_idx` ON `delivery_location_confirmations` (delivery_id, created_at DESC);
CREATE INDEX `idx_delivery_location_points_courier_time` ON `delivery_location_points` (courier_id, recorded_at);
CREATE INDEX `idx_delivery_location_points_delivery_time` ON `delivery_location_points` (delivery_id, recorded_at);
CREATE UNIQUE INDEX `delivery_offer_responses_delivery_id_courier_id_key` ON `delivery_offer_responses` (delivery_id, courier_id);
CREATE INDEX `delivery_responses_courier_index` ON `delivery_offer_responses` (courier_id);
CREATE INDEX `delivery_responses_delivery_index` ON `delivery_offer_responses` (delivery_id);
CREATE INDEX `delivery_payments_courier_idx` ON `delivery_payments` (courier_id, delivery_completed_at DESC);
CREATE UNIQUE INDEX `delivery_payments_delivery_id_key` ON `delivery_payments` (delivery_id);
CREATE INDEX `delivery_payments_status_idx` ON `delivery_payments` (status);
CREATE INDEX `delivery_payments_store_idx` ON `delivery_payments` (store_id, delivery_completed_at DESC);
CREATE INDEX `delivery_history_delivery_index` ON `delivery_status_history` (delivery_id);
CREATE INDEX `delivery_status_history_changed_by_idx` ON `delivery_status_history` (changed_by);
CREATE INDEX `idx_organization_members_user_id` ON `organization_members` (user_id, status);
CREATE INDEX `idx_organizations_owner_id` ON `organizations` (owner_id);
CREATE INDEX `platform_billing_settings_updated_by_idx` ON `platform_billing_settings` (updated_by);
CREATE INDEX `idx_platform_revenue_events_occurred_at` ON `platform_revenue_events` (occurred_at DESC);
CREATE INDEX `idx_platform_revenue_events_store_id` ON `platform_revenue_events` (store_id);
CREATE INDEX `platform_revenue_events_subscription_id_idx` ON `platform_revenue_events` (subscription_id);
CREATE UNIQUE INDEX `store_integrations_store_provider_key` ON `store_integrations` (store_id, provider);
CREATE INDEX `idx_store_members_user_id` ON `store_members` (user_id, status);
CREATE INDEX `idx_store_orders_store_received` ON `store_orders` (store_id, received_at DESC);
CREATE INDEX `idx_store_orders_store_source` ON `store_orders` (store_id, source, received_at DESC);
CREATE INDEX `idx_store_orders_store_status` ON `store_orders` (store_id, status, received_at DESC);
CREATE UNIQUE INDEX `store_subscriptions_store_id_key` ON `store_subscriptions` (store_id);
CREATE INDEX `idx_store_wallet_reservations_wallet_id` ON `store_wallet_reservations` (wallet_id);
CREATE INDEX `idx_wallet_reservations_store_status` ON `store_wallet_reservations` (store_id, status, created_at DESC);
CREATE UNIQUE INDEX `store_wallet_reservations_delivery_id_key` ON `store_wallet_reservations` (delivery_id);
CREATE INDEX `idx_store_wallet_topups_wallet_id` ON `store_wallet_topups` (wallet_id);
CREATE INDEX `idx_wallet_topups_store_status` ON `store_wallet_topups` (store_id, status, created_at DESC);
CREATE UNIQUE INDEX `store_wallet_topups_correlation_id_key` ON `store_wallet_topups` (correlation_id);
CREATE INDEX `idx_store_wallet_transactions_created_at` ON `store_wallet_transactions` (created_at DESC);
CREATE INDEX `idx_store_wallet_transactions_status` ON `store_wallet_transactions` (status);
CREATE INDEX `idx_store_wallet_transactions_store_id` ON `store_wallet_transactions` (store_id);
CREATE INDEX `idx_store_wallet_transactions_type` ON `store_wallet_transactions` (transaction_type);
CREATE INDEX `idx_store_wallet_transactions_wallet_id` ON `store_wallet_transactions` (wallet_id);
CREATE UNIQUE INDEX `store_wallets_store_id_key` ON `store_wallets` (store_id);
CREATE INDEX `idx_stores_organization_id` ON `stores` (organization_id);
CREATE INDEX `stores_moderated_by_idx` ON `stores` (moderated_by);
CREATE INDEX `stores_owner_id_idx` ON `stores` (owner_id);
CREATE INDEX `idx_whatsapp_credentials_waba` ON `whatsapp_connection_credentials` (waba_id);
CREATE UNIQUE INDEX `whatsapp_connection_credentials_phone_number_id_key` ON `whatsapp_connection_credentials` (phone_number_id);
CREATE INDEX `idx_whatsapp_conversations_store_last` ON `whatsapp_conversations` (store_id, last_message_at DESC);
CREATE UNIQUE INDEX `whatsapp_conversations_store_wa_key` ON `whatsapp_conversations` (store_id, wa_id);
CREATE INDEX `idx_whatsapp_messages_conversation_received` ON `whatsapp_messages` (conversation_id, received_at DESC);
CREATE INDEX `idx_whatsapp_messages_store_received` ON `whatsapp_messages` (store_id, received_at DESC);
CREATE UNIQUE INDEX `whatsapp_messages_provider_id_key` ON `whatsapp_messages` (provider_message_id);

SET FOREIGN_KEY_CHECKS = 1;
