-- Alinha bancos MySQL já existentes ao schema operacional atual do Supabase.
ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS phone VARCHAR(40) NULL AFTER full_name;

ALTER TABLE stores
  ADD COLUMN IF NOT EXISTS zip_code VARCHAR(30) NULL,
  ADD COLUMN IF NOT EXISTS street VARCHAR(180) NULL,
  ADD COLUMN IF NOT EXISTS street_number VARCHAR(40) NULL,
  ADD COLUMN IF NOT EXISTS complement VARCHAR(180) NULL,
  ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS organization_id CHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS moderated_at DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS moderated_by CHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS approved_at DATETIME(3) NULL;

ALTER TABLE couriers
  ADD COLUMN IF NOT EXISTS rating DECIMAL(4,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_deliveries INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_latitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS current_longitude DECIMAL(10,7) NULL,
  ADD COLUMN IF NOT EXISTS last_location_at DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(40) NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS moderation_reason TEXT NULL,
  ADD COLUMN IF NOT EXISTS moderated_at DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS moderated_by CHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS approved_at DATETIME(3) NULL;

ALTER TABLE deliveries
  ADD COLUMN IF NOT EXISTS seconds_to_accept INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS published_at DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS expires_at DATETIME(3) NULL,
  ADD COLUMN IF NOT EXISTS courier_batch_id CHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS target_courier_id CHAR(36) NULL,
  ADD COLUMN IF NOT EXISTS dispatch_route_group_id CHAR(36) NULL;
